# Site settings
title: The Type Index
email: jimmynotjim@me.com
description: > # this means to ignore newlines until "baseurl:"
  Mastering typography is difficult. The Type Index is here to help,
  as a permanant, public home for typographic resources,
  available for everyone to access and benefit from.
baseurl: /thetypeindex # the subpath of your site, e.g. /blog/
url: "http://thetypeindex.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
